### ISSUE TITLE
Getting error : Missing edgestore-ctx cookie

### ISSUE THREAD

**Issue by priya-jain-dev** [edgestorejs/edgestore#15]
While uploading single file getting error **Missing edgestore-ctx cookie** from API call.
I followed steps mention in : https://edgestore.dev/docs/components/image

**Comment by perfectbase** [comment]
Hi @priya-jain-dev!

I’m not sure what the problem might be.
Did you setup the provider correctly in the root of your app?
Can you take a look in your network tab to see if the `init` api is succeeding?

You can also try to run the example app in your machine.
Here are the steps to run the example app:
- clone the repo: `git clone https://github.com/edgestorejs/edgestore.git`
- cd into the example app: `cd examples/next-basic`
- run `npm install`
- add your environment variables to `examples/next-basic/.env.local`
- run `npm run dev`
- access the page at http://localhost:3000

Then compare it with your project and try to find the problem.

Let me know if this helps you.

**Comment by priya-jain-dev** [comment]
Hi @perfectbase  thanks for quick response.
`init` is returning token. But still getting 401 with upload api
<img width="1792" alt="image" src="https://github.com/edgestorejs/edgestore/assets/65802806/14be899e-9925-475d-82c6-ac9ab92b4bb5">

**Comment by priya-jain-dev** [comment]
Working now... Not sure how. 
After running small demo. I just restarted main project today without any change its working. Might be due to next cache.
