### ISSUE TITLE
thumbnailUrl is returning null, even though img uploaded is big

### ISSUE THREAD

**Issue by Farki** [edgestorejs/edgestore#16]
I uploaded multiple images various sizes and I keep getting thumbnailUrl: null

**Comment by perfectbase** [comment]
Hi @Farki,
Just making sure.. are you using an image bucket?
Thumbnails don’t work for file buckets.
If so, can you send me one of the images so I can test them here in one of the example apps?

**Comment by Farki** [comment]
@perfectbase oh yeah, I had file bucket.
Thanks 👍
