### ISSUE TITLE
Urgent: Mistakenly Uploaded Sensitive Document

### ISSUE THREAD

**Issue by azr-arch** [edgestorejs/edgestore#17]
Hello,

I was testing the multi-file components feature on EdgeStore.dev and mistakenly uploaded a document that contains sensitive private information. I realized my mistake immediately after the upload.

Due to the sensitive nature of the information, I cannot share the URL of the document publicly. I kindly request that someone from the support team reach out to me privately so we can resolve this issue as soon as possible.

I understand the severity of this situation and apologize for any inconvenience caused. I appreciate your prompt attention to this matter.

Thank you.

**Comment by perfectbase** [comment]
Hi @azr-arch 
Don't worry, no one can find out the url unless you share it with them.
If you can send an email to support@edgestore.dev sharing the url, I'll personally delete the file tomorrow without looking at its contents.

**Comment by azr-arch** [comment]
hey @perfectbase  Thank you for your reassurance. I have sent an email with the URL of the sensitive file. I appreciate your understanding and assistance in this matter.

**Comment by perfectbase** [comment]
@azr-arch I have deleted the file, and also invalidated the CDN cache for it, so that it is not accessible by anyone. Please check.
