### ISSUE TITLE
accessControl is giving me unauthorized

### ISSUE THREAD

**Issue by yousihy** [edgestorejs/edgestore#23]
Hello everyone!

I have been following the Youtube video tutorial for this amazing library and I was trying to implement the access control to protect the app images.

Now, the projection does not care about the user role or anything. I just need to make sure that the user is logged in regardless who he is.

The upload works great. But whenever I try to display the uploaded images in my app (with a logged in user), I get the unauthorized error.

Maybe I am doing something wong?

Here is the route.ts code:

```
import { currentUser, redirectToSignIn } from "@clerk/nextjs"
import { initEdgeStore } from "@edgestore/server"
import {
  CreateContextOptions,
  createEdgeStoreNextHandler,
} from "@edgestore/server/adapters/next/app"
import { z } from "zod"

context = {
  userId: string
}

async function createContext({ req }: CreateContextOptions): Promise<Context> {
  //logic to get the user from the session from clerk
  const user = await currentUser()
  if (user) {
    return {
      userId: user.id,
    }
  } else {
    return {
      userId: "Unknown",
    }
  }
}

const es = initEdgeStore.context<Context>().create()

const edgeStoreRouter = es.router({
  publicImages: es
    .imageBucket({
      maxSize: 1024 * 1024 * 1,
      accept: ["image/jpeg", "image/png"],
    })
    .input(
      z.object({
        type: z.enum(["post", "profile", "market"]),
      })
    )
    //example: /post/my-post.jpg
    .path(({ input }) => [{ type: input.type }])
    .accessControl({
      userId: { not: "Unknown" },
    }),
})
const handler = createEdgeStoreNextHandler({
  router: edgeStoreRouter,
  createContext,
})
export { handler as GET, handler as POST }

export type EdgeStoreRouter = typeof edgeStoreRouter

```

**Comment by perfectbase** [comment]
Hi @yousihy!

I just tested it here with a similar setup, but I couldn't replicate the problem.
I believe the configuration is correct.

Some things you could try to narrow the problem down:
- reload the page a few times (this will make sure that the initial load happens after the cookie is already set)
- take a look at your network tab to see if the `init` request is succeeding
- put some logs in the createContext, so you know exactly what's being set
- try calling the `reset` function before showing the images

```ts
const { edgestore, reset } = useEdgeStore();

async function runAfterAuthChange() {
  await reset(); // this will re-run the createContext function
}
```

Other thing.. There was is a bug for accessControl in production environments (with https) in the current version. It's unrelated to this problem, but you might want to update your package.json to:

```
"@edgestore/react": "^0.1.5-alpha.5",
"@edgestore/server": "^0.1.5-alpha.5",
```

this should become stable soon.

Let me know if this helps you solve the problem

**Comment by perfectbase** [comment]
@yousihy I just created a simple example app with access control in a way that only signed in users can see the images.

https://github.com/edgestorejs/edgestore/assets/103035973/b1b61ee7-d285-4490-9646-d77b8dd5f6d0

Here is the router configuration:

```ts
import { initEdgeStore } from '@edgestore/server';
import {
  createEdgeStoreNextHandler,
  type CreateContextOptions,
} from '@edgestore/server/adapters/next/app';
import { initEdgeStoreClient } from '@edgestore/server/core';
import { cookies } from 'next/headers';
import { z } from 'zod';

type Context = {
  signedIn: 'true' | 'false';
};

function createContext(_opts: CreateContextOptions): Context {
  const signedIn = cookies().get('signedIn')?.value ?? 'false';
  return {
    signedIn: signedIn === 'true' ? 'true' : 'false',
  };
}

const es = initEdgeStore.context<Context>().create();

/**
 * This is the main router for the Edge Store buckets.
 */
const edgeStoreRouter = es.router({
  privateFiles: es
    .fileBucket({
      accept: ['image/*'],
    })
    .input(z.object({ type: z.enum(['post', 'article']) }))
    .path(({ input }) => [{ type: input.type }])
    .accessControl({
      signedIn: { not: 'false' },
    }),
});

const handler = createEdgeStoreNextHandler({
  router: edgeStoreRouter,
  createContext,
});

export { handler as GET, handler as POST };

/**
 * This type is used to create the type-safe client for the frontend.
 */
export type EdgeStoreRouter = typeof edgeStoreRouter;

export const backendClient = initEdgeStoreClient({
  router: edgeStoreRouter,
  baseUrl: 'http://localhost:3000/api/edgestore',
});
```

You can run this example in your machine with the following steps:
- clone the repo
- checkout to the `next` branch
- cd into the `examples/basic-access-control` folder
- add your environment variables to `.env.local`
- `npm install`
- `npm run dev`
- access it in `http://localhost:3000`

> I am unable to delete the Bucket from the Edgestore now that it is protected and I don't want to create a new Bucket. How to do that?
Sorry. This is a missing feature in the dashboard. It will be added eventually, but right now all you can do is ignore the old bucket or delete and recreate the whole project.

**Comment by yousihy** [comment]
Hey! thanks for the updated code. I tried your code after changing the auth logic to use Clerk and instead of using fileBucket, I used the imageBucket.

I first tried to upload 1 image. And it worked. I was able to see the image. Then I tried uploading two images, both are getting 500. I am not sure why it is working for the first image but not for subsequent images:

<img width="635" alt="image" src="https://github.com/edgestorejs/edgestore/assets/70659920/204421e6-e720-44e7-bbe8-b7af9c4e5b74">

After this, ALL image uploads are getting the 500. I tried to reload the app, restart the server, clear the cashe ... nothing worked.

HOWEVER! By mere luck! I looked at the code and I decided to try loading the images using the `url `and not the `thumbnailUrl`, and it worked! :)

```
<MultiFileDropzoneSimple
                      loadingImages={isUploading}
                      value={fileStates}
                      onChange={(files) => {
                        setFileStates(files)
                      }}
                      onFilesAdded={async (addedFiles) => {
                        setFileStates([...fileStates, ...addedFiles])
                        setIsUploading(true)
                        await Promise.all(
                          addedFiles.map(async (addedFileState) => {
                            try {
                              const res =
                                await edgestore.privateFilesTest.upload({
                                  file: addedFileState.file,
                                  options: {
                                    temporary: true,
                                  },
                                  input: { type: "unit" },
                                  onProgressChange: async (progress) => {
                                    updateFileProgress(
                                      addedFileState.key,
                                      progress
                                    )
                                    if (progress === 100) {
                                      await new Promise((resolve) =>
                                        setTimeout(resolve, 1000)
                                      )
                                      updateFileProgress(
                                        addedFileState.key,
                                        "COMPLETE"
                                      )
                                    }
                                  },
                                })
                              setUploadedFiles((uploadedFiles) => [
                                ...uploadedFiles,
                                {
                                  url: res.url,
                                  thumbnailUrl: res.thumbnailUrl,
                                },
                              ])
                            } catch (err) {
                              updateFileProgress(addedFileState.key, "ERROR")
                            }
                          })
                        )
                        setIsUploading(false)
                      }}
                    />
                  </div>
                  {uploadedFiles.length > 0 && (
                    <div className="grid grid-cols-4 mt-5 gap-2">
                      {uploadedFiles.map((file) => (
                        <div
                          key={file.thumbnailUrl || file.url}
                          className="relative w-full h-40 bg-gray-100 rounded-md overflow-hidden"
                        >
                          <img
                            src={file.thumbnailUrl || file.url}
                            className="absolute inset-0 w-full h-full object-cover"
                          />
                        </div>
                      ))}
                    </div>
                  )}
```

I update the below section to use url instead:

```
 setUploadedFiles((uploadedFiles) => [
                                ...uploadedFiles,
                                {
                                  url: res.url,
                                  thumbnailUrl: res.url,
                                },
                              ])
```

And everything is working now:

<img width="650" alt="image" src="https://github.com/edgestorejs/edgestore/assets/70659920/fc2aa4d9-04dc-4427-a007-621630331617">

Am I doing something wrong when it comes to setting or reading the `thumbnailUrl`?

**Comment by perfectbase** [comment]
@yousihy 
>HOWEVER! By mere luck! I looked at the code and I decided to try loading the images using the url and not the thumbnailUrl, and it worked! :)

Interesting! I'll investigate as soon as I can.

Some things to be aware of when using thumbnails (probably unrelated to the problem):
- Thumbnails are only created for image buckets.
- Thumbnails are not always created. They are created only for images larger than a certain size.
- Thumbnails may take a few seconds to be created after the upload finishes, so if you try to use it as soon as the upload ends, it might still be unaccessible.

That said... I haven't tried using thumbnails with a protected image bucket, there might be a bug in there. I'll let you know when I take a look.

**Comment by perfectbase** [comment]
I'll close this issue for now.
If you have any other problems feel free to let me know.
