### ISSUE TITLE
delete files on the server side

### ISSUE THREAD

**Issue by chrishoermann** [edgestorejs/edgestore#26]
Thanks for this nice and easy to user uploader.
I don't know if i missed something in the docs but is it possible to delete files from the server e.g. after a database entry was deleted the corresponding files should also be deleted. 
To me it would make sense to delete the files in the same place the corresponding database entries get deleted and not in the frontend.

**Comment by perfectbase** [comment]
Hi @chrishoermann!
Glad you are enjoying the service!

Yes! There is a backend client that you can use for that. It is still under development but should be out soon on the next official release.
There are still no docs for it.

Take a look at this issue for more information information: https://github.com/edgestorejs/edgestore/issues/24

If all you want to do is delete the file, you should be able to do it with the version you are currently using. But if you also want to upload files, you will need to upgrade to the alpha version. The latest one is `^0.1.5-alpha.8`.

**Comment by chrishoermann** [comment]
Thanks, got it!
