### ISSUE TITLE
How to view the files on the other end once uploaded...?

### ISSUE THREAD

**Issue by aaa3334** [edgestorejs/edgestore#29]
So I have a feeling I just wasted time and spent time figuring this out only to not be able to access the files afterwards..
I can find a lot of docs on how to upload the files but I cant find anything showing how to display the files again... I am assuming there is a particular api i should call or something but cant seem to figure it out....
Any idea if this is possible or if the docs could be updated with an example of this?

**Comment by perfectbase** [comment]
Hi @aaa3334,

Ideally your app has its own database, and you will save the url in the response of the upload method to it, so you can retrieve it later.

That said, there is a way to retrieve the uploaded files by using the beta backend client. (this will be officially released soon and added to the docs.)

You can export the backend client from your api route:

```ts
// app/api/edgestore/[...edgestore]/route.ts
import { initEdgeStoreClient } from '@edgestore/server/core';

// ...

export const backendClient = initEdgeStoreClient({
  router: edgeStoreRouter,
});
```

Then you can use the listFiles function to list files from your backend. It's also possible to filter the results by path, metadata or upload timing.

```ts
// simple usage
// get the first page (20 files) of all files in the bucket
const res = await backendClient.publicFiles.listFiles();

// with filter and pagination
const res = await backendClient.publicFiles.listFiles({
  filter: {
    metadata: {
      role: 'admin',
    },
    path: {
      type: 'post',
    },
    uploadedAt: {
      gt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7), // past 7 days
    },
  },
  pagination: {
    currentPage: 1, // default: 1
    pageSize: 50, // default: 20 (max: 100)
  },
});
```

There is also an example in the repo that uses this `listFiles` function here:
https://github.com/edgestorejs/edgestore/blob/main/examples/basic-access-control/src/app/page.tsx#L20-L24

Let me know if it helps.

**Comment by perfectbase** [comment]
The backend client is officially released and in the docs.

https://edgestore.dev/docs/backend-client

I'll close this for now. If you have any problems feel free to open a new issue.
