### ISSUE TITLE
Is there a way to dynamically Set S3 Bucket? 

### ISSUE THREAD

**Issue by copyPasteNinja** [edgestorejs/edgestore#33]
I have a multi tenant nextjs app that stores documents, I need to store each document into different S3 Buckets based on what client is user session. I'm trying to find a way to dynamically set S3 Bucket name before each upload, if thats even possible...

Any ideas? I could really use some guide here 🙏 

(Happy Holidays)

**Comment by perfectbase** [comment]
Hi @copyPasteNinja!

I'm guessing you are using the AWS Provider, right?

I have never tried it, but I believe it would be possible if you wrap the handler into your own handler.
something like this:

```ts
const handler = (request: NextRequest) => {
  const tenant = request.cookies.get('tenant');

  const bucketName = `bucket-for-${tenant}`;

  return createEdgeStoreNextHandler({
    provider: AWSProvider({
      bucketName,
    }),
    router: edgeStoreRouter,
  });
};
```

this is for the app router, but it would be very similar for the pages router.
I haven't tested the code, if you have problems, let me know.
