### ISSUE TITLE
Ip blocking

### ISSUE THREAD

**Issue by JohnWebKilla** [edgestorejs/edgestore#37]
HI team , for some reason when I try to access the edge store website or even fetch my files from the storage its blocking my ip unless I use VPN. Why is this happening ?  On Phone network its working fine, but on my pc office internet is blocking

**Comment by perfectbase** [comment]
Hi @JohnWebKilla !
Edge Store doesn't have ip blocking feature.
Is it possible that your office internet has some security configuration that doesn't allow access to some unknown services?
