### ISSUE TITLE
Are there any Edgestore's website source code?

### ISSUE THREAD

**Issue by ilyabumblebee** [edgestorejs/edgestore#38]
Hello!

I'd like to know whether the frontend code for Edgestore's website is or will be accessible.

Thanks!

**Comment by perfectbase** [comment]
Hi @ilyabumblebee 
If you want the landing page and docs code. You can find everything in this repo, under the docs folder.

In case you are looking for the dashboard app and infrastructure code, than no, that part is not open source. There are no plans to open source it.
