### ISSUE TITLE
Service only working on localhost

### ISSUE THREAD

**Issue by bstenm** [edgestorejs/edgestore#42]
Only works on localhost, when I deploy the application to a real url the api route returns a 500 internal server error.

`http://localhost:4200/api/edgestore/health`
returns "OK" as expected.

`https://mysite/api/edgestore/health`
returns "500 | Internal Server Error."

**Comment by perfectbase** [comment]
Hi @bstenm 
That's strange. There are many production apps running with edgestore, so it's hard to think that it is a problem with the service or the package.

I'm not sure what could be the problem here.
If you have a minimal reproducible example for me to try, I may be able to help. (Something that doesn't need additional infrastructure)

You can also check the example app deployed to production here:

https://examples.edgestore.dev/components

And here is the health check endpoint

https://examples.edgestore.dev/components/api/edgestore/health

**Comment by bstenm** [comment]
I deployed using Aws Amplify. To reproduce the issue:

Create a new nextjs app:
`npx create-next-app@latest`

Install Edgestore:
`npm install @edgestore/server @edgestore/react zod`

Follow the Edgestore quickstart for the files:
`src/app/api/edgestore/[...edgestore]/route.ts`
`src/lib/edgestore.ts`
`src/app/layout.tsx`

Run the app locally, the health endpoint (http://localhost:3000/api/edgestore/health) returns "OK".

Add your app to a github repository.

Add a new application to Aws Amplify pointing to your github repo.

Add the Edgestore environment variables (EDGE_STORE_ACCESS_KEY and EDGE_STORE_SECRET_KEY) in the App Settings panel.

Click "Save and Deploy".

After successful deployment, open the url set by Amplify, the health endpoint (in my case: https://main.d6b249jh0042b.amplifyapp.com/api/edgestore/health) returns a 500.

**Comment by perfectbase** [comment]
Hi @bstenm 

Sorry that your having problems.
I have no access to any logs or code on your side so it's hard for me to help.

Again, if you could try to run one of the example apps, maybe you can figure out what is the problem.
Take a look at this page here: https://edgestore.dev/docs/troubleshooting

If you have a minimal reproducible repo for me to take a look at, I might be able to help.

**Comment by bstenm** [comment]
[perfectbase](https://github.com/perfectbase)
Ok, I got the cloudwatch logs working and as I expected it seems on the deployed site Edgestore does not find the enviromnent variables even though I entered them in the App Setting panel dedicated for that. Here is the error message:
```
⨯ th [EdgeStoreCredentialsError]: Missing EDGE_STORE_ACCESS_KEY or EDGE_STORE_SECRET_KEY. 
This can happen if you are trying to import something related to the backend of Edge Store in a client component.
at /var/task/.next/server/app/api/edgestore/[...edgestore]/route.js:4:51229
at /var/task/.next/server/app/api/edgestore/[...edgestore]/route.js:4:53869
at 37623 (/var/task/.next/server/app/api/edgestore/[...edgestore]/route.js:4:56801)
at t (/var/task/.next/server/webpack-runtime.js:1:142)
at r (/var/task/.next/server/app/api/edgestore/[...edgestore]/route.js:4:59911)
at /var/task/.next/server/app/api/edgestore/[...edgestore]/route.js:4:59938
at t.X (/var/task/.next/server/webpack-runtime.js:1:1270)
at /var/task/.next/server/app/api/edgestore/[...edgestore]/route.js:4:59924
at Object.<anonymous> (/var/task/.next/server/app/api/edgestore/[...edgestore]/route.js:4:59966)
at Module._compile (node:internal/modules/cjs/loader:1356:14)
```
I checked that indeed the env variables are correctly passed to the `process.env`, so could it be somehow something with the way Edgestore access them on initialization?

**Comment by perfectbase** [comment]
@bstenm Edge Store just uses the environment variables from the process.env

This is probably a problem with how amplify sets environment variables.

Did you try to console.log the environment variables from inside the server-side of your app?
(Remember that server-side and client-side environment variables are different)

Maybe this is something related to your problem:
https://stackoverflow.com/questions/68010336/using-next-js-with-ssr-on-aws-amplify-environment-variables-not-being-carried-t

**Comment by perfectbase** [comment]
Glad it worked! Thanks for reporting it. I might add it in the docs eventually.
