### ISSUE TITLE
Product website isn't working.

### ISSUE THREAD

**Issue by Eh1z** [edgestorejs/edgestore#43]
When I go to this "https://edgestore.dev/" URL for the documentation and other things, It says "This site can’t be reached".

I want to use this in a production-ready project and I am kind of worried, was the website URL changed or the hosting plans expired?
![Screenshot_select-area_20240310100906](https://github.com/edgestorejs/edgestore/assets/111048723/0c10ceef-49a3-44d5-928b-ca0450f2d08b)

**Comment by perfectbase** [comment]
Hi @Eh1z
The website is up and running on the url you are trying!
Are you trying to access it from your work environment?
Maybe your work pc or network has some security settings blocking the connection?

**Comment by Eh1z** [comment]
It's from my PC, 
I can access https://dashboard.edgestore.dev/ but still can't open the main website i.e. https://edgestore.dev/

I have no network security on my current network, same thing on every browser I try and my phone.

**Comment by perfectbase** [comment]
@Eh1z 
O also just tried from multiple devices and multiple browsers, I can access it with no problems. Also no one else from the community is reporting this, so I believe it is a very specific problem.

If you can't access it from multiple devices, the only thing I can think of is that your public IP is being blocked from Vercel?

But the dashboard app is also deployed to Vercel, so it would be only for the docs app which is also kind of strange.

By the way, what is the region you are accessing from?
Could you try to use some free VPN service to access it from another country's IP?

**Comment by Eh1z** [comment]
Thank you for responding, I tried a UK location on a VPN and it worked. Must be a regional thing.

I am accessing from Nigeria by the way.

**Comment by Eh1z** [comment]
Thank you for responding, I tried a UK location on a VPN and it worked. Must be a regional thing.

I am accessing from Nigeria by the way.

**Comment by aaa3334** [comment]
I have the same issue today with this accessing it from Australia with safari. Was working before..

![Screenshot 2024-03-14 at 10 21 59](https://github.com/edgestorejs/edgestore/assets/63257282/2c4aed06-9bdf-4502-9420-edfd2c4ff6a3)
