### ISSUE TITLE
Works perfectly on production but not working on development (localhost)

### ISSUE THREAD

**Issue by Aikay-dev** [edgestorejs/edgestore#44]
when i try to use localhost, i get the following errors in my console

1. index.mjs:355 
 POST https://localhost:3000/api/edgestore/init 500 (Internal Server Error)

2. Uncaught (in promise) EdgeStoreApiClientError: Internal server error
    at handleError (index.mjs:25:11)
    at async init (index.mjs:389:17)

when i test localhost with https://localhost:3000/api/edgestore/health, i get ok, same as prod

what can be the issue

**Comment by perfectbase** [comment]
Hi @Aikay-dev 

Are you using a `createContext` function in your app?
It could be that the create context is failing locally.
What are the server side error logs?

The example apps should work locally. You can try to run them in your computer and try to figure out what's the difference to your project.
Take a look at the troubleshooting docs for more information here:
https://edgestore.dev/docs/troubleshooting

If you can't figure it out, you can also create a minimal reproducible repo (something that doesn't need additional infrastructure to run) so I can try it out to find the problem.

Hope it helps.

**Comment by Aikay-dev** [comment]
@perfectbase i solved the issue by using a vpn, i noticed i couldnt access the https://edgestore.dev/ website, but when i used a vpn, the site worked, and my code also started working on localhost. I live in nigeria btw. Thanks for  the help
