### ISSUE TITLE
Product website not working - Internet Provider blocking the site?

### ISSUE THREAD

**Issue by aaa3334** [edgestorejs/edgestore#45]
Hi!

I know this is a repeat but I am still getting the same error as in the other post and the issue is closed so I don't think I would get a reply there... I have done a little investigation as to when I can access the website and when I cannot. I don't understand the reason for it but have looked into it a little at least:

1) Trying generally no matter the browser does not work and I get the following error:

This is what the error looks like on brave:
<img width="1131" alt="Screenshot 2024-03-18 at 08 33 24" src="https://github.com/edgestorejs/edgestore/assets/63257282/cd47edb2-ae13-402c-a54d-2ee1c9ad9a19">

The 'advanced' error on that says:

"edgestore.dev normally uses encryption to protect your information. When Brave tried to connect to edgestore.dev this time, the website sent back unusual and incorrect credentials. This may happen when an attacker is trying to pretend to be edgestore.dev, or a Wi-Fi sign-in screen has interrupted the connection. Your information is still secure because Brave stopped the connection before any data was exchanged.

You cannot visit edgestore.dev right now because the website uses HSTS. Network errors and attacks are usually temporary, so this page will probably work later."

I tried late last week, but it seems like the error is still happening.

This is the error on Firefox (safari's is just very plain and general as was chromes)
<img width="767" alt="Screenshot 2024-03-18 at 08 45 04" src="https://github.com/edgestorejs/edgestore/assets/63257282/2e9ca75c-b5fe-43d9-8fc6-de7ead083327">
(note I reported it to the telstra 'report this website as safe' here: https://www.telstra.com.au/forms/report-misuse-of-service)

2) If I try on my phone when it is connected to my home wifi it does not work
3) If I try on my phone when not connected to the home wifi it works
4) If I try with a vpn, it works

I have no clue what is causing the issue but it might be telstra blocking the site, however given there was another report of it, it seems like there might be something causing the website being flagged by ISP's... So might be worthwhile figuring out the security issue or why it is being flagged suddenly (was working about a month ago for me at least)

No clue if this could help, but if the website is not accessible to people you are going to lose out on customers/people using it.

**Comment by Sof2222** [comment]
Seems like its working again now in Australia at least! Not sure what the problem was

**Comment by Sof2222** [comment]
Unsure how to close the issue now... cant seem to see how. But feel free to close!
