### ISSUE TITLE
Error when starting next-intl issue

### ISSUE THREAD

**Issue by Gabrieldsantos96** [edgestorejs/edgestore#48]
index.mjs:23 Uncaught (in promise) EdgeStoreError: Failed to parse response. Make sure the api is correctly configured at http://localhost:3000/api/edgestore/init
    at handleError (index.mjs:23:15)
    
  
![image](https://github.com/edgestorejs/edgestore/assets/94016081/fb8b5d98-7869-414a-af75-cc86b998be5c)

all things are setted, but i think im getting error because next-intl, since there's a [locale] folder, i suspect edgestore is not finding because of that, there's a working round for this ? btw i tried to put api folder inside and outside locale.

**Comment by TheCypher** [comment]
Hi @Gabrieldsantos96 did you ever solve this issue?

**Comment by perfectbase** [comment]
I just tried it with next-intl and confirmed that it works out of the box without the need for any change in the Edge Store setup.
I also added an example app with next-intl just in case: https://github.com/edgestorejs/edgestore/tree/main/examples/next-basic-with-intl
