### ISSUE TITLE
Thumbnail rotated

### ISSUE THREAD

**Issue by EarthShaping** [edgestorejs/edgestore#49]
I have noticed that sometimes the thumbnail is rotated. Here is an image where I can encounter this problem
![test](https://github.com/edgestorejs/edgestore/assets/5947051/28cc5997-17e4-48ba-8977-41e5b21dddec)

**Comment by perfectbase** [comment]
I was able to reproduce the issue here! Thank you for reporting it.
I'll take a look at it.

**Comment by perfectbase** [comment]
@EarthShaping The issue should be fixed now! If you have any other problems, please let me know!
