### ISSUE TITLE
Path and Filter doesn't work together

### ISSUE THREAD

**Issue by Arslan-Soomro** [edgestorejs/edgestore#51]
I am using edge store, and I cannot filter items using both the metadata and path prop together, you can use them individually when listing files, but when you use them together it returns nothing, just an empty array, although there are files that match that criteria. 
For now, as a workaround I just get all the files on a certain path and filter them myself using javascript, which comes with two drawbacks
1. Its not an efficient way
2. I can no longer use pagination
3. User requests take a long time, since I have to first get all the files (imagine if the files are in thousands), and then filter them.

For Example, this filter wouldn't work, because it uses metadata and path properties at the same time.
```js
filter: {
      metadata: {
            category: "other"
       },
       path: {
            entityId: entityId,
          },
      }
```

**Comment by perfectbase** [comment]
Hi @Arslan-Soomro 
Thank you for reporting this!
Will check it as soon as I can.

**Comment by perfectbase** [comment]
Hi @Arslan-Soomro 
I think this is the filter you are looking for.
```js
filter: {
  AND: [
    {
      metadata: {
        category: "other"
      },
    },
    {
      path: {
        entityId: entityId,
      },
    },
  ],
},
```
Can you check if this works for you?

Maybe it's a good idea to also make it work the way you wrote it.

**Comment by Arslan-Soomro** [comment]
This filter also doesn't work, behaves exactly like the one I mentioned earlier

**Comment by perfectbase** [comment]
@Arslan-Soomro You're right! Sorry for the trouble and thanks for reporting the issue.
I was able to reproduce and fix it.
There was a problem with the function that builds the `where` query based on the filter json.
This should work as expected now. (both filter patterns work)

```ts
filter: {
  AND: [
    {
      metadata: {
        category: "other",
      },
    },
    {
      path: {
        entityId: entityId,
      },
    },
  ],
},

// or

filter: {
  metadata: {
    category: "other",
  },
  path: {
    entityId: entityId,
  },
},
```

Could you try it again?

**Comment by Arslan-Soomro** [comment]
Thank You @perfectbase for pointing that out. I updated the edgestore packages and It started working. The query builder syntax, can come in handy. But I couldn't figure out how it works. I had to filter the files in the metadata with either "other" or "general" in category.
I tried something like
`
        filter: {
          AND: [
            {
              OR: [
                {
                  metadata: {
                    category: "other"
                  },
                },
                {
                  metadata: {
                    category: "general"
                  },
                },
              ],
            },
            {
              path: {
                userId: user.id,
              },
            },
          ],
        },  
`

**Comment by perfectbase** [comment]
@Arslan-Soomro I just tested this filter pattern here and it works as expected.

Maybe the problem is with the value you are passing to the `userId`?
Could you log it to see the exact values being passed to the filter?

Also, if you can post the zod error details, maybe it can help.

In my example app:
```ts
filter: {
  AND: [
    {
      OR: [
        {
          metadata: {
            role: 'visitor',
          },
        },
        {
          metadata: {
            role: 'admin',
          },
        },
      ],
    },
    {
      path: {
        author: '234',
      },
    },
  ],
},
```

**Comment by Arslan-Soomro** [comment]
I just copy pasted your filter and adjusted it to work the way I wanted it with userId and metadata and it worked. I don't know what the issue was, but its fixed. Also I wanted to ask if we could filter files that don't have a specific metadata field attached with them. E.g. all files without a category field in the metadata, I initially thought passing `null` would do the trick, but it didn't work, instead I got a zod error, that category can only be string and not null. Am I doing something wrong, or is there different way to do?
```js
// I initially thought this would work, but it doesn't
filter: {
   metadata: {
        category: null
   }
}
```

**Comment by perfectbase** [comment]
@Arslan-Soomro Glad it worked!

Sorry, right now you can't filter by null.

The metadata and path were designed to be present as a string for every file with no null values. But this doesn't actually happen since you can change the bucket configuration after a few files were already uploaded.

There are definitely some improvements to be made here.
But I think it should be made as another issue.
I'll add this to my internal tasks here. If you want, you can open a new issue for the enhancement of the filter logic.

**Comment by Arslan-Soomro** [comment]
Thank you so much @perfectbase. You were a great help! Keep up the good work with edgestore 👍
