### ISSUE TITLE
How to change base url in next js?

### ISSUE THREAD

**Issue by rohitkrishna094** [edgestorejs/edgestore#57]
I followed the quick start guide: https://edgestore.dev/docs/quick-start

However instead of putting the code inside /api folder, I put the code in /a folder because in my project I am using /a as api routes. Yet the upload is failing because its calling /api/edgestore/request-upload

Is there a way to customize this so that it doesnt always only call /api/something?

**Comment by perfectbase** [comment]
Hi @rohitkrishna094 

Yes! You can configure the base path for your api.
You can check it out here:

https://edgestore.dev/docs/configuration#base-path
