### ISSUE TITLE
Third-party cookie will be blocked in future Chrome versions as part of Privacy Sandbox

### ISSUE THREAD

**Issue by hapnan** [edgestorejs/edgestore#61]
I get a warning in the console, after a few uplouds, and after that I can't uploud anymore and the warning appears.

![image](https://github.com/user-attachments/assets/ebbccafa-0a63-4776-b0fd-3f3278be2abb)

**Comment by perfectbase** [comment]
hi @hapnan 
I tried to follow up on the [Discord thread](https://discord.com/channels/1060144459431559208/1273324565011107841/1273425116033974272), but there was no response, so I'll close the issue for now.
Let me know if you still have any problems.

I'll also paste the discord response here:

> Third party cookies are only needed for accessing protected files, so I believe these warnings are unrelated to the problem.
> 
> Can you check and share these informations?
> check the requests on the network tab
> check the server side logs
> maybe activate the debug logs to see it in more details
> 
> You can see how to activate the debug logs here:
> https://edgestore.dev/docs/troubleshooting
