### ISSUE TITLE
next-js build error

### ISSUE THREAD

**Issue by Premlak** [edgestorejs/edgestore#62]
when we try to deploy our project and run npm run build or next build we get errors like
at /vercel/path0/.next/server/app/api/edgestore/[...edgestore]/route.js:4:51836
    at /vercel/path0/.next/server/app/api/edgestore/[...edgestore]/route.js:4:54476
    at 93214 (/vercel/path0/.next/server/app/api/edgestore/[...edgestore]/route.js:4:57249)
    at t (/vercel/path0/.next/server/webpack-runtime.js:1:143)
    at r (/vercel/path0/.next/server/app/api/edgestore/[...edgestore]/route.js:9:2100)
    at /vercel/path0/.next/server/app/api/edgestore/[...edgestore]/route.js:9:2128
    at t.X (/vercel/path0/.next/server/webpack-runtime.js:1:1285)
    at /vercel/path0/.next/server/app/api/edgestore/[...edgestore]/route.js:9:2113
    at Object.<anonymous> (/vercel/path0/.next/server/app/api/edgestore/[...edgestore]/route.js:9:2156)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
> Build error occurred
Error: Failed to collect page data for /api/edgestore/[...edgestore]
    at /vercel/path0/node_modules/next/dist/build/utils.js:1268:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'Error'

**Comment by perfectbase** [comment]
Hi @Premlak 

I'm not sure what this could be just by looking at the error.
Does the app work normally on `npm run dev`?

You can try the troubleshooting docs:
https://edgestore.dev/docs/troubleshooting

It also has steps to run the example apps, so that you can compare it with your project.

If nothing helps, please share a minimal reproducible repo so that I can debug the problem on my environment.

**Comment by Premlak** [comment]
> Hi @Premlak
> 
> I'm not sure what this could be just by looking at the error. Does the app work normally on `npm run dev`?
> 
> You can try the troubleshooting docs: https://edgestore.dev/docs/troubleshooting
> 
> It also has steps to run the example apps, so that you can compare it with your project.
> 
> If nothing helps, please share a minimal reproducible repo so that I can debug the problem on my environment.

Yes its working fine with npm run dev . Only when i try to deploy the project then i face the issue at the path /app/api/edgestore/[...edgestore] and i spent approx 5 hours on debugging and other tools also from the official website. But none of these things worked for me

**Comment by perfectbase** [comment]
@Premlak Sorry to hear that!

If you try with one of the example apps, you will see that it should build fine.
The task will be to find the difference between your project and the example app that is causing the issue.

If you make a minimal reproducible repo, let me know and I'll gladly take a look at it.

**Comment by Premlak** [comment]
> @Premlak Sorry to hear that!
> 
> If you try with one of the example apps, you will see that it should build fine. The task will be to find the difference between your project and the example app that is causing the issue.
> 
> If you make a minimal reproducible repo, let me know and I'll gladly take a look at it.

Yes sure, you can take a look at the repo https://github.com/Premlakshay/Sutudy-Platform and by the you can also try to deploy it because its a public repo.

**Comment by perfectbase** [comment]
@Premlak Sorry... A repo with your whole project makes it difficult to find the problem if it is related to Edge Store.
I tried to clone it, but it failed on the `npm install` command.

Could you try to make a minimal reproducible repo from one of the example apps?
(like this one: https://github.com/edgestorejs/edgestore/tree/main/examples/next-basic)

**Comment by perfectbase** [comment]
I'm going to close this issue for inactivity.
If you still have problems, let me know.
