### ISSUE TITLE
Metadata Full Text Search

### ISSUE THREAD

**Issue by Arslan-Soomro** [edgestorejs/edgestore#64]
Is there a way to perform a full text search with metadata, my use case is I need to provide the users with a search capability, so the user can search files, and reach the file they need easily. I have a filename field in metadata.

**Comment by perfectbase** [comment]
Hi @Arslan-Soomro 

No. There is no full text search on the files metadata.
Right now I don't have plans to add this feature.

For a more flexible search, I would recommend that you include the metadata inside your own db and make the search from there.
