### ISSUE TITLE
500 Error, While Emptying a bucket from dashboard

### ISSUE THREAD

**Issue by Arslan-Soomro** [edgestorejs/edgestore#65]
<img width="1290" alt="image" src="https://github.com/user-attachments/assets/2980a289-6058-424a-a707-b62f3d97e7a2" />

**Comment by perfectbase** [comment]
@Arslan-Soomro Thank you for reporting the issue. It seems that the API is timing out. I think I might be able to improve the related queries to fix this. I'll also try to plan a way that will make it work even for larger buckets.

**Comment by Arslan-Soomro** [comment]
> @Arslan-Soomro Could you please try again? I’ve made some immediate improvements. It’s not perfect yet, but it might be sufficient for this bucket. If the error occurs again, check if the number of files in the bucket has been reduced. If it has, you can run the process multiple times to complete the job. (I know, not the ideal solution.)

Just tried, still the same error.

**Comment by perfectbase** [comment]
@Arslan-Soomro Really sorry for all the trouble... Could you try just one last time? I just release another improvement.
If it doesn't work, you can request that I empty your bucket from my side. I'll keep working on improving this to avoid future problems.

**Comment by Arslan-Soomro** [comment]
> @Arslan-Soomro Really sorry for all the trouble... Could you try just one last time? I just released another improvement. If it doesn't work, you can request that I empty your bucket from my side. I'll keep working on improving this to avoid future problems.

I tried,and still got the same error. You may remove the bucket from your side.

**Comment by perfectbase** [comment]
@Arslan-Soomro really sorry for the trouble! 🙏 I deleted all files from the bucket on my side.
Let me know if you need anything else.

**Comment by Arslan-Soomro** [comment]
> @Arslan-Soomro really sorry for the trouble! 🙏 I deleted all files from the bucket on my side. Let me know if you need anything else.

Thank You, The files are deleted now.
